#!/usr/bin/env bash

# Install HAProxy
sudo apt-get install -y haproxy

# Enable management via the init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Backup the original config file
sudo mv /etc/haproxy/haproxy.cfg{,.original}

# Create a new HAProxy configuration file
sudo touch /etc/haproxy/haproxy.cfg

# Populate the configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
global
    log 127.0.1 local0 notice
    maxconn 200
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 30000
    timeout server 30000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/400.http
    errorfile 408 /etc/haproxy/errors/400.http
    errorfile 500 /etc/haproxy/errors/400.http
    errorfile 502 /etc/haproxy/errors/400.http
    errorfile 503 /etc/haproxy/errors/400.http
    errorfile 504 /etc/haproxy/errors/400.http

frontend http-in
    timeout client 30000
    bind 0:80
    default_backend servers

backend servers
    timeout connect 3000
    timeout server 30000
    balance roundrobin
    server 401824-web-01 54.146.63.145:80 check
    server 401824-web-02 3.90.70.209:80 check
EOF
